import { CropSubmission, SupplierRow, SystemLog } from './types';

export const INITIAL_CROP_LOGS: CropSubmission[] = [
  {
    id: 'crop-101',
    cropName: 'Punjab Basmati Rice (Premium Long Grain)',
    farmerName: 'Muhammad Arshad',
    location: 'Sargodha, Punjab',
    quantityTons: 120,
    waterSavingsPct: 42,
    sustainabilityScore: 'A+',
    submissionDate: '2026-05-24 14:10',
    status: 'Approved',
  },
  {
    id: 'crop-102',
    cropName: 'Aseel Dates (Premium Sweet)',
    farmerName: 'Zainab Khairpur',
    location: 'Khairpur, Sindh',
    quantityTons: 85,
    waterSavingsPct: 35,
    sustainabilityScore: 'A',
    submissionDate: '2026-05-24 15:30',
    status: 'Pending',
  },
  {
    id: 'crop-103',
    cropName: 'Organic Alfalfa Al-Ahsa Feed',
    farmerName: 'Faisalabad Agro',
    location: 'Faisalabad, Punjab',
    quantityTons: 335,
    waterSavingsPct: 38,
    sustainabilityScore: 'A+',
    submissionDate: '2026-05-23 09:45',
    status: 'In-Transit',
  }
];

export const SUPPLIER_DATA: SupplierRow[] = [
  {
    id: 'sup-001',
    supplierName: 'Al-Sajjad Basmati Group',
    location: 'Gujranwala, Punjab',
    cropType: 'Punjab Basmati Rice',
    quantityAvailableTons: 250,
    sustainabilityScore: 'A+',
    waterSavingsPct: 45,
    carbonReductionTons: 12.4,
    pricePerTonUSD: 850,
    logisticsPathway: 'Karachi Port (PK) ➔ Jidda Islamic Port (SA) Sea Freight',
  },
  {
    id: 'sup-002',
    supplierName: 'Khairpur Oasis Palms',
    location: 'Khairpur, Sindh',
    cropType: 'Organic Sindh Dates (Aseel & Sukkuri)',
    quantityAvailableTons: 180,
    sustainabilityScore: 'A',
    waterSavingsPct: 38,
    carbonReductionTons: 8.2,
    pricePerTonUSD: 1200,
    logisticsPathway: 'Karachi Port (PK) ➔ Jidda Islamic Port (SA) Sea Freight',
  },
  {
    id: 'sup-003',
    supplierName: 'Indus Valley Agro-Federation',
    location: 'Multan, Punjab',
    cropType: 'Non-GMO Corn Seed',
    quantityAvailableTons: 400,
    sustainabilityScore: 'B+',
    waterSavingsPct: 30,
    carbonReductionTons: 15.1,
    pricePerTonUSD: 410,
    logisticsPathway: 'Karachi Port (PK) ➔ Dammam Port (SA) Sea Freight',
  },
  {
    id: 'sup-004',
    supplierName: 'Karak Mountain Bee Keepers',
    location: 'Karak, Khyber Pakhtunkhwa',
    cropType: 'Sidr Honey (A+ Export Grade)',
    quantityAvailableTons: 25,
    sustainabilityScore: 'A++',
    waterSavingsPct: 52,
    carbonReductionTons: 4.6,
    pricePerTonUSD: 9500,
    logisticsPathway: 'Peshawar Air Cargo (PK) ➔ Riyadh King Khalid Int (SA)',
  }
];

export const INITIAL_SYSTEM_LOGS: SystemLog[] = [
  {
    id: 'log-100',
    timestamp: '16:48:42',
    apiName: 'System Edge',
    method: 'GET',
    endpoint: '/edge-routing/lat-test',
    latencyMs: 12,
    status: '200 OK',
    payload: '{"status":"active", "edgeNode":"Karachi-Jidda-Pipeline"}',
  },
  {
    id: 'log-101',
    timestamp: '16:49:15',
    apiName: 'Cohere.ai API',
    method: 'POST',
    endpoint: '/v1/rerank/semantic-weights',
    latencyMs: 145,
    status: '200 OK',
    payload: '{"query": "organic dates from khairpur", "top_n": 4, "candidates": 8}',
  },
  {
    id: 'log-102',
    timestamp: '16:50:02',
    apiName: 'Gemini API',
    method: 'POST',
    endpoint: '/v1beta/models/gemini-2.5-flash:generateContent',
    latencyMs: 310,
    status: '200 OK',
    payload: '{"task": "parse_farm_certificate", "origin": "Pakistan Federal Department of Agriculture"}',
  },
  {
    id: 'log-103',
    timestamp: '16:50:48',
    apiName: 'Groq API',
    method: 'POST',
    endpoint: '/v1/chat/completions',
    latencyMs: 180,
    status: '200 OK',
    payload: '{"model": "llama-3-70b-versatile", "prompt_tokens": 1284, "completion_tokens": 425}',
  }
];
